--------------------------------------------------------
-- Archivo creado  - martes-mayo-26-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_CIUDAD
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_CIUDAD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_COMUNA
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_COMUNA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_DOCUMENTO
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_DOCUMENTO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_FAMILIA_PROD
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_FAMILIA_PROD"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_FORMA_PAGO
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_FORMA_PAGO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ORDN_COMPRA
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_ORDN_COMPRA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PRODUCTOS
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_PRODUCTOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 181 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PRODUCTO_VENTA
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_PRODUCTO_VENTA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PROVEEDOR
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_PROVEEDOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 180 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_RECEPCION
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_RECEPCION"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_REGION
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_REGION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_RUBRO
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_RUBRO"  MINVALUE 1 MAXVALUE 999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_STS_ORDN_COMPRA
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_STS_ORDN_COMPRA"  MINVALUE 1 MAXVALUE 99999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SUBFAMILIA_PROD
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_SUBFAMILIA_PROD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TIPO_DOCUMENTO
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_TIPO_DOCUMENTO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TIPO_PROV
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_TIPO_PROV"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USERARIOS
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_USERARIOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1680 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USER_ROL
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_USER_ROL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_VENTA
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SEQ_VENTA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CIUDAD
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."CIUDAD" 
   (	"ID_CIUDAD" NUMBER(10,0) DEFAULT "PORTAFOLIO"."SEQ_CIUDAD"."NEXTVAL", 
	"CIUDAD" VARCHAR2(50 BYTE), 
	"ID_REGION" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMUNA
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."COMUNA" 
   (	"ID_COMUNA" NUMBER(10,0) DEFAULT "PORTAFOLIO"."SEQ_COMUNA"."NEXTVAL", 
	"COMUNA" VARCHAR2(50 BYTE), 
	"ID_CIUDAD" NUMBER(10,0) DEFAULT "PORTAFOLIO"."SEQ_CIUDAD"."NEXTVAL"
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DOCUMENTO
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."DOCUMENTO" 
   (	"ID_DOCUMENTO" NUMBER(10,0) DEFAULT "PORTAFOLIO"."SEQ_DOCUMENTO"."NEXTVAL", 
	"ID_TIPO_DOCUMENTO" NUMBER(10,0), 
	"FECHA_DOCUMENTO" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESTADO_ORDEN_COMPRA
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."ESTADO_ORDEN_COMPRA" 
   (	"ID_ESTADO_ORDEN_COMPRA" NUMBER(10,0) DEFAULT "PORTAFOLIO"."SEQ_STS_ORDN_COMPRA"."NEXTVAL", 
	"ESTADO_ORDEN_COMPRA" VARCHAR2(20 BYTE), 
	"FECHA_ESTADO_ORDEN_COMPRA" DATE, 
	"ID_ORDEN_COMPRA" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FAMILIA_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."FAMILIA_PRODUCTO" 
   (	"ID_FAMILIA_PRODUCTO" NUMBER(10,0) DEFAULT "PORTAFOLIO"."SEQ_FAMILIA_PROD"."NEXTVAL", 
	"FAMILIA_PRODUCTO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FORMA_PAGO
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."FORMA_PAGO" 
   (	"ID_FORMA_PAGO" NUMBER(10,0) DEFAULT "PORTAFOLIO"."SEQ_FORMA_PAGO"."NEXTVAL", 
	"FORMA_PAGO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDEN_COMPRA
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."ORDEN_COMPRA" 
   (	"ID_ORDEN_COMPRA" NUMBER(10,0) DEFAULT "PORTAFOLIO"."SEQ_ORDN_COMPRA"."NEXTVAL", 
	"FECHA_COMPRA" DATE, 
	"ID_USUARIO" NUMBER(10,0), 
	"ID_RECEPCION" NUMBER(10,0), 
	"ID_PRODUCTO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."PRODUCTO" 
   (	"ID_PRODUCTO" NUMBER(10,0) DEFAULT "PORTAFOLIO"."SEQ_PRODUCTOS"."NEXTVAL", 
	"CODIGO_PRODUCTO" NUMBER(20,0) DEFAULT 0, 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"PRECIO" NUMBER(20,0) DEFAULT 0, 
	"STOCK" NUMBER(10,0) DEFAULT 0, 
	"ID_PROVEEDOR" NUMBER(10,0), 
	"ID_SUBFAMILIA_PRODUCTO" NUMBER(10,0), 
	"MARCA_PRODUCTO" VARCHAR2(30 BYTE), 
	"HABILITADO" CHAR(1 BYTE) DEFAULT 1, 
	"IMAGEN_PRODUCTO" VARCHAR2(100 BYTE), 
	"FECHA_VENCIMIENTO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO_VENTA
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."PRODUCTO_VENTA" 
   (	"ID_PRODUCTO_VENTA" NUMBER(10,0) DEFAULT "PORTAFOLIO"."SEQ_PRODUCTO_VENTA"."NEXTVAL", 
	"ID_PRODUCTO" NUMBER(10,0), 
	"CANTIDAD" NUMBER(10,0) DEFAULT 0, 
	"ID_VENTA" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROVEEDOR
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."PROVEEDOR" 
   (	"ID_PROVEEDOR" NUMBER(10,0) DEFAULT "PORTAFOLIO"."SEQ_PROVEEDOR"."NEXTVAL", 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"RUT_PROVEEDOR" NUMBER(8,0), 
	"DV_RUT_PROVEEDOR" CHAR(1 BYTE), 
	"DIRECCION" VARCHAR2(100 BYTE), 
	"RAZON_SOCIAL" VARCHAR2(50 BYTE) DEFAULT - NULL, 
	"ID_RUBRO" NUMBER(10,0), 
	"CELULAR" NUMBER(9,0), 
	"ID_COMUNA" NUMBER(10,0), 
	"ID_USUARIO" NUMBER(10,0), 
	"HABILITADO" CHAR(1 BYTE) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RECEPCION
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."RECEPCION" 
   (	"ID_RECEPCION" NUMBER(10,0) DEFAULT "PORTAFOLIO"."SEQ_RECEPCION"."NEXTVAL", 
	"ID_USUARIO" NUMBER(10,0), 
	"FECHA_RECEPCION" DATE, 
	"OBSERVACIONES" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REGI�N
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."REGI�N" 
   (	"ID_REGI�N" NUMBER(10,0) DEFAULT "PORTAFOLIO"."SEQ_REGION"."NEXTVAL", 
	"REGION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROL
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."ROL" 
   (	"ID_ROL" NUMBER(10,0), 
	"TIPO_ROL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RUBRO
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."RUBRO" 
   (	"ID_RUBRO" NUMBER(10,0) DEFAULT "PORTAFOLIO"."SEQ_RUBRO"."NEXTVAL", 
	"TIPO_RUBRO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUBFAMILIA_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."SUBFAMILIA_PRODUCTO" 
   (	"ID_SUBFAMILIA_PRODUCTO" NUMBER(10,0) DEFAULT "PORTAFOLIO"."SEQ_SUBFAMILIA_PROD"."NEXTVAL", 
	"SUBFAMILIA_PRODUCTO" VARCHAR2(30 BYTE), 
	"ID_FAMILIA_PRODUCTO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_DOCUMENTO
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."TIPO_DOCUMENTO" 
   (	"ID_TIPO_DOCUMENTO" NUMBER(10,0) DEFAULT "PORTAFOLIO"."SEQ_TIPO_DOCUMENTO"."NEXTVAL", 
	"TIPO_DOCUMENTO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."USUARIO" 
   (	"ID_USUARIO" NUMBER(10,0) DEFAULT "PORTAFOLIO"."SEQ_USERARIOS"."NEXTVAL", 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO" VARCHAR2(50 BYTE), 
	"RUT_USUARIO" NUMBER(8,0), 
	"DV_USUARIO" CHAR(1 BYTE), 
	"SEXO_USUARIO" CHAR(1 BYTE), 
	"FECHA_NACIMIENTO_USUARIO" DATE, 
	"PASS_USUARIO" VARCHAR2(100 BYTE), 
	"CORREO_ELECTRONICO" VARCHAR2(50 BYTE), 
	"DIRECCION" VARCHAR2(50 BYTE), 
	"ID_COMUNA" NUMBER(10,0), 
	"HABILITADO" CHAR(1 BYTE) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIO_ROL
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."USUARIO_ROL" 
   (	"ID_USUARIO_ROL" NUMBER(10,0) DEFAULT "PORTAFOLIO"."SEQ_USER_ROL"."NEXTVAL", 
	"ID_USUARIO" NUMBER(10,0), 
	"ID_ROL" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VENTA
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."VENTA" 
   (	"ID_VENTA" NUMBER(10,0) DEFAULT "PORTAFOLIO"."SEQ_VENTA"."NEXTVAL", 
	"ID_USUARIO" NUMBER(10,0), 
	"ID_DOCUMENTO" NUMBER(10,0), 
	"ID_FORMA_PAGO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CIUDAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."CIUDAD_PK" ON "PORTAFOLIO"."CIUDAD" ("ID_CIUDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMUNA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."COMUNA_PK" ON "PORTAFOLIO"."COMUNA" ("ID_COMUNA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DOCUMENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."DOCUMENTO_PK" ON "PORTAFOLIO"."DOCUMENTO" ("ID_DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ESTADO_ORDEN_COMPRA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."ESTADO_ORDEN_COMPRA_PK" ON "PORTAFOLIO"."ESTADO_ORDEN_COMPRA" ("ID_ESTADO_ORDEN_COMPRA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FAMILIA_PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."FAMILIA_PRODUCTO_PK" ON "PORTAFOLIO"."FAMILIA_PRODUCTO" ("ID_FAMILIA_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FORMA_PAGO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."FORMA_PAGO_PK" ON "PORTAFOLIO"."FORMA_PAGO" ("ID_FORMA_PAGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDEN_COMPRA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."ORDEN_COMPRA_PK" ON "PORTAFOLIO"."ORDEN_COMPRA" ("ID_ORDEN_COMPRA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PEDIDO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."PEDIDO_PK" ON "PORTAFOLIO"."VENTA" ("ID_VENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCTO_PEDIDO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."PRODUCTO_PEDIDO_PK" ON "PORTAFOLIO"."PRODUCTO_VENTA" ("ID_PRODUCTO_VENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."PRODUCTO_PK" ON "PORTAFOLIO"."PRODUCTO" ("ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROVEEDOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."PROVEEDOR_PK" ON "PORTAFOLIO"."PROVEEDOR" ("ID_PROVEEDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RECEPCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."RECEPCION_PK" ON "PORTAFOLIO"."RECEPCION" ("ID_RECEPCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REGI�N_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."REGI�N_PK" ON "PORTAFOLIO"."REGI�N" ("ID_REGI�N") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."ROL_PK" ON "PORTAFOLIO"."ROL" ("ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RUBRO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."RUBRO_PK" ON "PORTAFOLIO"."RUBRO" ("ID_RUBRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SUBFAMILIA_PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."SUBFAMILIA_PRODUCTO_PK" ON "PORTAFOLIO"."SUBFAMILIA_PRODUCTO" ("ID_SUBFAMILIA_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TIPO_DOCUMENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."TIPO_DOCUMENTO_PK" ON "PORTAFOLIO"."TIPO_DOCUMENTO" ("ID_TIPO_DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."USUARIO_PK" ON "PORTAFOLIO"."USUARIO" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIO_ROL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."USUARIO_ROL_PK" ON "PORTAFOLIO"."USUARIO_ROL" ("ID_USUARIO_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."USUARIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIO" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIO" MODIFY ("RUT_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIO" MODIFY ("DV_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIO" MODIFY ("SEXO_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIO" MODIFY ("PASS_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIO" ADD CONSTRAINT "USUARIO_PK" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."USUARIO" MODIFY ("CORREO_ELECTRONICO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIO" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIO" MODIFY ("ID_COMUNA" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIO" MODIFY ("HABILITADO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIO" MODIFY ("FECHA_NACIMIENTO_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REGI�N
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."REGI�N" MODIFY ("ID_REGI�N" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."REGI�N" MODIFY ("REGION" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."REGI�N" ADD CONSTRAINT "REGI�N_PK" PRIMARY KEY ("ID_REGI�N")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VENTA
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."VENTA" MODIFY ("ID_VENTA" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."VENTA" ADD CONSTRAINT "PEDIDO_PK" PRIMARY KEY ("ID_VENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."VENTA" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."VENTA" MODIFY ("ID_DOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."VENTA" MODIFY ("ID_FORMA_PAGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."PRODUCTO" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PRODUCTO" MODIFY ("CODIGO_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PRODUCTO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PRODUCTO" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PRODUCTO" MODIFY ("STOCK" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PRODUCTO" MODIFY ("ID_PROVEEDOR" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PRODUCTO" ADD CONSTRAINT "PRODUCTO_PK" PRIMARY KEY ("ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."PRODUCTO" MODIFY ("MARCA_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PRODUCTO" MODIFY ("ID_SUBFAMILIA_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PRODUCTO" MODIFY ("HABILITADO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROL
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."ROL" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."ROL" MODIFY ("TIPO_ROL" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."ROL" ADD CONSTRAINT "ROL_PK" PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTADO_ORDEN_COMPRA
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."ESTADO_ORDEN_COMPRA" MODIFY ("ID_ESTADO_ORDEN_COMPRA" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."ESTADO_ORDEN_COMPRA" MODIFY ("ESTADO_ORDEN_COMPRA" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."ESTADO_ORDEN_COMPRA" ADD CONSTRAINT "ESTADO_ORDEN_COMPRA_PK" PRIMARY KEY ("ID_ESTADO_ORDEN_COMPRA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."ESTADO_ORDEN_COMPRA" MODIFY ("ID_ORDEN_COMPRA" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."ESTADO_ORDEN_COMPRA" MODIFY ("FECHA_ESTADO_ORDEN_COMPRA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTO_VENTA
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."PRODUCTO_VENTA" MODIFY ("ID_PRODUCTO_VENTA" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PRODUCTO_VENTA" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PRODUCTO_VENTA" ADD CONSTRAINT "PRODUCTO_PEDIDO_PK" PRIMARY KEY ("ID_PRODUCTO_VENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."PRODUCTO_VENTA" MODIFY ("ID_VENTA" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PRODUCTO_VENTA" MODIFY ("CANTIDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RUBRO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."RUBRO" MODIFY ("ID_RUBRO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."RUBRO" MODIFY ("TIPO_RUBRO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."RUBRO" ADD CONSTRAINT "RUBRO_PK" PRIMARY KEY ("ID_RUBRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROVEEDOR
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."PROVEEDOR" MODIFY ("ID_PROVEEDOR" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PROVEEDOR" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PROVEEDOR" MODIFY ("RUT_PROVEEDOR" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PROVEEDOR" MODIFY ("DV_RUT_PROVEEDOR" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PROVEEDOR" ADD CONSTRAINT "PROVEEDOR_PK" PRIMARY KEY ("ID_PROVEEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."PROVEEDOR" MODIFY ("CELULAR" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PROVEEDOR" MODIFY ("RAZON_SOCIAL" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PROVEEDOR" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PROVEEDOR" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PROVEEDOR" MODIFY ("ID_COMUNA" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PROVEEDOR" MODIFY ("ID_RUBRO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PROVEEDOR" MODIFY ("HABILITADO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECEPCION
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."RECEPCION" MODIFY ("ID_RECEPCION" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."RECEPCION" ADD CONSTRAINT "RECEPCION_PK" PRIMARY KEY ("ID_RECEPCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."RECEPCION" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."RECEPCION" MODIFY ("FECHA_RECEPCION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUBFAMILIA_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."SUBFAMILIA_PRODUCTO" MODIFY ("ID_SUBFAMILIA_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."SUBFAMILIA_PRODUCTO" MODIFY ("SUBFAMILIA_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."SUBFAMILIA_PRODUCTO" MODIFY ("ID_FAMILIA_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."SUBFAMILIA_PRODUCTO" ADD CONSTRAINT "SUBFAMILIA_PRODUCTO_PK" PRIMARY KEY ("ID_SUBFAMILIA_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPO_DOCUMENTO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."TIPO_DOCUMENTO" MODIFY ("ID_TIPO_DOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."TIPO_DOCUMENTO" MODIFY ("TIPO_DOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."TIPO_DOCUMENTO" ADD CONSTRAINT "TIPO_DOCUMENTO_PK" PRIMARY KEY ("ID_TIPO_DOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDEN_COMPRA
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."ORDEN_COMPRA" MODIFY ("ID_RECEPCION" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."ORDEN_COMPRA" MODIFY ("ID_ORDEN_COMPRA" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."ORDEN_COMPRA" MODIFY ("FECHA_COMPRA" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."ORDEN_COMPRA" ADD CONSTRAINT "ORDEN_COMPRA_PK" PRIMARY KEY ("ID_ORDEN_COMPRA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."ORDEN_COMPRA" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."ORDEN_COMPRA" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FORMA_PAGO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."FORMA_PAGO" MODIFY ("ID_FORMA_PAGO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."FORMA_PAGO" MODIFY ("FORMA_PAGO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."FORMA_PAGO" ADD CONSTRAINT "FORMA_PAGO_PK" PRIMARY KEY ("ID_FORMA_PAGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FAMILIA_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."FAMILIA_PRODUCTO" MODIFY ("ID_FAMILIA_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."FAMILIA_PRODUCTO" MODIFY ("FAMILIA_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."FAMILIA_PRODUCTO" ADD CONSTRAINT "FAMILIA_PRODUCTO_PK" PRIMARY KEY ("ID_FAMILIA_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMUNA
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."COMUNA" MODIFY ("ID_CIUDAD" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."COMUNA" MODIFY ("ID_COMUNA" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."COMUNA" MODIFY ("COMUNA" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."COMUNA" ADD CONSTRAINT "COMUNA_PK" PRIMARY KEY ("ID_COMUNA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CIUDAD
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."CIUDAD" MODIFY ("ID_CIUDAD" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."CIUDAD" MODIFY ("CIUDAD" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."CIUDAD" ADD CONSTRAINT "CIUDAD_PK" PRIMARY KEY ("ID_CIUDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."CIUDAD" MODIFY ("ID_REGION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOCUMENTO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."DOCUMENTO" MODIFY ("ID_DOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."DOCUMENTO" ADD CONSTRAINT "DOCUMENTO_PK" PRIMARY KEY ("ID_DOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."DOCUMENTO" MODIFY ("ID_TIPO_DOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."DOCUMENTO" MODIFY ("FECHA_DOCUMENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIO_ROL
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."USUARIO_ROL" MODIFY ("ID_USUARIO_ROL" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIO_ROL" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIO_ROL" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIO_ROL" ADD CONSTRAINT "USUARIO_ROL_PK" PRIMARY KEY ("ID_USUARIO_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CIUDAD
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."CIUDAD" ADD CONSTRAINT "FK_REGI�N" FOREIGN KEY ("ID_REGION")
	  REFERENCES "PORTAFOLIO"."REGI�N" ("ID_REGI�N") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMUNA
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."COMUNA" ADD CONSTRAINT "FK_CIUDAD" FOREIGN KEY ("ID_CIUDAD")
	  REFERENCES "PORTAFOLIO"."CIUDAD" ("ID_CIUDAD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DOCUMENTO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."DOCUMENTO" ADD CONSTRAINT "FK_TIPO_DOCUMENTO" FOREIGN KEY ("ID_TIPO_DOCUMENTO")
	  REFERENCES "PORTAFOLIO"."TIPO_DOCUMENTO" ("ID_TIPO_DOCUMENTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTADO_ORDEN_COMPRA
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."ESTADO_ORDEN_COMPRA" ADD CONSTRAINT "FK_ORDEN_COMPRA_ESTADO" FOREIGN KEY ("ID_ORDEN_COMPRA")
	  REFERENCES "PORTAFOLIO"."ORDEN_COMPRA" ("ID_ORDEN_COMPRA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDEN_COMPRA
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."ORDEN_COMPRA" ADD CONSTRAINT "FK_USUARIO_ORDEN" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "PORTAFOLIO"."USUARIO" ("ID_USUARIO") ENABLE;
  ALTER TABLE "PORTAFOLIO"."ORDEN_COMPRA" ADD CONSTRAINT "FK_PRODUCTO_ORDEN" FOREIGN KEY ("ID_PRODUCTO")
	  REFERENCES "PORTAFOLIO"."PRODUCTO" ("ID_PRODUCTO") ENABLE;
  ALTER TABLE "PORTAFOLIO"."ORDEN_COMPRA" ADD CONSTRAINT "FK_RECEPCION_ORDEN" FOREIGN KEY ("ID_RECEPCION")
	  REFERENCES "PORTAFOLIO"."RECEPCION" ("ID_RECEPCION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."PRODUCTO" ADD CONSTRAINT "FK_PROVEEDOR" FOREIGN KEY ("ID_PROVEEDOR")
	  REFERENCES "PORTAFOLIO"."PROVEEDOR" ("ID_PROVEEDOR") ENABLE;
  ALTER TABLE "PORTAFOLIO"."PRODUCTO" ADD CONSTRAINT "FK_SUBFAMILIA_PRODUCTO" FOREIGN KEY ("ID_SUBFAMILIA_PRODUCTO")
	  REFERENCES "PORTAFOLIO"."SUBFAMILIA_PRODUCTO" ("ID_SUBFAMILIA_PRODUCTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTO_VENTA
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."PRODUCTO_VENTA" ADD CONSTRAINT "FK_PRODUCTO" FOREIGN KEY ("ID_PRODUCTO")
	  REFERENCES "PORTAFOLIO"."PRODUCTO" ("ID_PRODUCTO") ENABLE;
  ALTER TABLE "PORTAFOLIO"."PRODUCTO_VENTA" ADD CONSTRAINT "FK_VENTA" FOREIGN KEY ("ID_VENTA")
	  REFERENCES "PORTAFOLIO"."VENTA" ("ID_VENTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROVEEDOR
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."PROVEEDOR" ADD CONSTRAINT "FK_COMUNA" FOREIGN KEY ("ID_COMUNA")
	  REFERENCES "PORTAFOLIO"."COMUNA" ("ID_COMUNA") ENABLE;
  ALTER TABLE "PORTAFOLIO"."PROVEEDOR" ADD CONSTRAINT "FK_USUARIO_PROVEEDOR" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "PORTAFOLIO"."USUARIO" ("ID_USUARIO") ENABLE;
  ALTER TABLE "PORTAFOLIO"."PROVEEDOR" ADD CONSTRAINT "FK_RUBRO_PROVEEDOR" FOREIGN KEY ("ID_RUBRO")
	  REFERENCES "PORTAFOLIO"."RUBRO" ("ID_RUBRO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECEPCION
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."RECEPCION" ADD CONSTRAINT "FK_USUARIO_RECEPCION" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "PORTAFOLIO"."USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBFAMILIA_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."SUBFAMILIA_PRODUCTO" ADD CONSTRAINT "FK_FAMILIA_PRODUCTO" FOREIGN KEY ("ID_FAMILIA_PRODUCTO")
	  REFERENCES "PORTAFOLIO"."FAMILIA_PRODUCTO" ("ID_FAMILIA_PRODUCTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."USUARIO" ADD CONSTRAINT "FK_COMUNA_USUARIO" FOREIGN KEY ("ID_COMUNA")
	  REFERENCES "PORTAFOLIO"."COMUNA" ("ID_COMUNA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIO_ROL
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."USUARIO_ROL" ADD CONSTRAINT "FK_USUARIO_ROL" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "PORTAFOLIO"."USUARIO" ("ID_USUARIO") ENABLE;
  ALTER TABLE "PORTAFOLIO"."USUARIO_ROL" ADD CONSTRAINT "FK_ROL" FOREIGN KEY ("ID_ROL")
	  REFERENCES "PORTAFOLIO"."ROL" ("ID_ROL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VENTA
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."VENTA" ADD CONSTRAINT "FK_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "PORTAFOLIO"."USUARIO" ("ID_USUARIO") ENABLE;
  ALTER TABLE "PORTAFOLIO"."VENTA" ADD CONSTRAINT "FK_DOCUMENTO" FOREIGN KEY ("ID_DOCUMENTO")
	  REFERENCES "PORTAFOLIO"."DOCUMENTO" ("ID_DOCUMENTO") ENABLE;
  ALTER TABLE "PORTAFOLIO"."VENTA" ADD CONSTRAINT "FK_FORMA_PAGO" FOREIGN KEY ("ID_FORMA_PAGO")
	  REFERENCES "PORTAFOLIO"."FORMA_PAGO" ("ID_FORMA_PAGO") ENABLE;
